- hosts: localhost
  name: Macbook Playbook
  gather_facts: False
  vars:
    TFENV_ARCH: amd64
  tasks:
    - name: Ensures taps are present via homebrew
      community.general.homebrew_tap:
        name: "{{ item }}"
        state: present
      with_items:
        - hashicorp/tap

    - name: Ensures packages are present via homebrew cask
      community.general.homebrew_cask:
        name: "{{ item }}"
        state: present
        install_options: "appdir=/Applications"
      with_items:
        - spotify
        - keycastr
        - iterm2
        - tableplus
        - whatsapp
        - discord
        - docker

    - name: Ensures packages are present via homebrew
      community.general.homebrew:
        name: "{{ item }}"
        state: present
        path: "/Applications"
      with_items:
        - git
        - git-lfs
        - wget
        - xz
        - zlib
        - jq
        - yq
        - awscli
        - aws-sso-util
        - aws-vault
        - asdf
        - ruby
        - erlang
        - elixir
        - postgresql
        - node
        - nvm
        - fzf
        - ripgrep
        - tmux
        - neovim
        - openssl
      ignore_errors: yes
      tags:
        - packages
